judge0:
    api:
        url: http://localhost:2358
    client:
        connect-timeout: 5000
        response-timeout: 10000
        read-timeout: 10000
        write-timeout: 10000
    allowed-language-ids: [52, 62, 71]
    max-source-size-bytes: 65536

spring:
    application:
        name: OnlineJudgeCode

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true

    datasource:
        url: jdbc:mysql://localhost:3301/onlineJudgeWeb?useSSL=false&serverTimezone=UTC
        username: root
        password: nguyen2005

app:
    jwt:
        secret: "Ab17031991@#icomefromHanoicityandIloveyouWhatdoyoumeanAhihihi"
        expiration: 8640000000
        refresh-expiration: 2592000000

quiz:
    admin:
        email: admin@gmail.com
        password: A123456a@
