judge0:
    api:
        url: http://localhost:2358

spring:
    application:
        name: OnlineJudgeCode

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3301/onlineJudgeWeb?useSSL=false&serverTimezone=UTC}
        username: ${SPRING_DATASOURCE_USERNAME:root}
        password: ${SPRING_DATASOURCE_PASSWORD:nguyen2005}

app:
    jwt:
        secret: ${APP_JWT_SECRET:Ab17031991@#icomefromHanoicityandIloveyouWhatdoyoumeanAhihihi}
        expiration: ${APP_JWT_EXPIRATION:8640000000}
        refresh-expiration: ${APP_JWT_REFRESH_EXPIRATION:2592000000}
    cors:
        allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

quiz:
    admin:
        email: admin@gmail.com
        password: A123456a@
